### ISSUE TITLE
Infra: AWS Autoscaling

### ISSUE THREAD

**Issue by jimpick** [ipfs/testground#154]
The Terraform scripts already have the workers configured in an Autoscaling group with a manual strategy.

To get the clusters to "scale in" when not in use, we could use a custom autoscaling strategy:

https://docs.aws.amazon.com/autoscaling/plans/userguide/gs-configure-scaling-plan.html

It seems we could simply publish a custom metric (perhaps with the desired container count?) to AWS Cloudwatch and hook the autoscaling strategy to that:

https://docs.aws.amazon.com/autoscaling/plans/userguide/gs-specify-custom-settings.html

The only thing the new nodes need to do on startup is setup filebeat and join the docker swarm. We could fetch the needed data from the manager machine which is always up (I think we can give it a common static IP in the VPC).

When the cluster does a "scale in" (we should probably only do this when no jobs are running), we'll get orphaned entries in the docker swarm node table, so to keep things tidy, we'll want to periodically remove them, perhaps with a daily cron job.

We could have a script to manually set the CloudWatch network for times when we want the cluster to be scaled out even when no jobs are running.

**Comment by dirkmc** [comment]
I remember Edgar mentioning that we should be careful about scaling up and down too much as it can cause inconsistent results in benchmarks. @hinshun could you confirm?

**Comment by hinshun** [comment]
It's not the benchmarks per-say, but we observed higher number of failures with ASGs bigger than 200 nodes. I think combined with the `libp2p` connection bugs, it was hard to configure the network topology reliably.

Small clusters (like 3 peers) may have some inconsistent results because `bitswap` may end up transferring all data only from 1 peer. This doesn't occur in bigger clusters (4+).

I suggest you opt-in to the beta EC2 limits based on vCPUs because it's much easier to manage than requesting limit increases on every instance type you want to scale higher in.

**Comment by jimpick** [comment]
Yep, I requested a raise to 128 vCPUs and got it ... might need to get that raised again if we go really big. I'm new to this aspect of AWS. :-)

**Comment by daviddias** [comment]
I'm not sure if I understand why would we use auto scaling in the first place. The test plan writer should have control over the number instances created for the test case (number of docker containers spawned, each with an independent node) and how over many machines those instances are going to be instantiated (during the step of setting up the cluster).

**Comment by jimpick** [comment]
Related PR: #175 

As the cluster "scales out", the worker nodes will automatically configure themselves and join the swarm.

**Comment by jimpick** [comment]
The primary immediate use case for autoscaling is to scale the cluster to zero workers when inactive ... Jeff Bezos has too much money already.

**Comment by daviddias** [comment]
I understand your point (on saving $$ however, that puts at risk the reproducibility of each test as we can't tell:

- When auto scaling fires
- How fast it will boot new machines
- If the Docker Containers started will move smoothly to the new machines.

Because of this open questions and the lack of ability to mitigate the concerns within them, we should not use auto-scaling.

**Comment by jimpick** [comment]
PR #210 does away with autoscaling groups, so I'm closing this.
