### ISSUE TITLE
REDIS_HOST isn't consistently set

### ISSUE THREAD

**Issue by Stebalien** [ipfs/testground#285]
The sidecar is broken on the latest master using any runner except k8s. We need to consistently set REDIS_HOST.

**Comment by nonsense** [comment]
I guess this is due to https://github.com/ipfs/testground/pull/280 , but I don't understand what the `sidecar` has to do with various `runners`. Whoever starts the `sidecar` (a developer manually, or some infrastructure script on Docker Swarm, or k8s), it should be setting the ENV var, no? The sidecar is assumed to be available at the time you run a `testground run` command with a given testplan, right?

**Comment by Stebalien** [comment]
Fixed.
