### ISSUE TITLE
Test Multus-CNI (and another CNI) with k8s

### ISSUE THREAD

**Issue by daviddias** [ipfs/testground#295]
https://intel.github.io/multus-cni/

**Comment by nonsense** [comment]
I have tested Multus CNI with Flannel CNI, on a self-managed Kubernetes cluster (created with `kops`) with two networks and it works.

In order to run two (or more) networks, we need to be running multiple `flanneld` daemons on every host - https://coreos.com/flannel/docs/latest/running.html#multiple-networks

Once setup you can annotate pods when creating them, and they attach to the default Kubernetes network and to the secondary network, for example:

```
➜  kops git:(master) ✗ kubectl exec -it samplepod bash
[root@samplepod /]# ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 8951
        inet 100.96.2.3  netmask 255.255.255.0  broadcast 0.0.0.0
        ether 86:04:a3:0b:7f:b9  txqueuelen 0  (Ethernet)

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
...

net1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 8951
        inet 10.0.2.2  netmask 255.255.255.0  broadcast 0.0.0.0
        ether d6:ec:10:32:38:5d  txqueuelen 0  (Ethernet)

[root@samplepod /]#
```

I tried running the `sidecar` on this cluster, but get to the following error:
```
Dec 20 11:18:39.141772  ERROR   sidecar worker failed: when initializing the container: failed to resolve route to redis: network is unreachable        {"host": "unix:///var/run/docker.sock", "container": "792e774aee29f35bd2454bdb0a93d7cd
220189f5e3eac9fa8ce323e82ee0b67a"}
github.com/ipfs/testground/pkg/dockermanager.(*Manager).Manage.func3.1
        /pkg/dockermanager/dockermanager.go:135
```

It looks like the sidecar would need updating if we decide to not use Docker networks, because it is listing networks and filtering from the container manager, but `net1` interface (and its network) is not a Docker network. Another point worth mentioning is that so far I tried only one additional secondary overlay network to the default Kubernetes network (both running with Flannel), whereas currently we create a new Docker network for every testplan run.

cc @Stebalien

**Comment by raulk** [comment]
I would support removing need for sidecar to interact with the Docker daemon to list and identify networks. If flannel gives us subnet configuration, we could detect which network is which by IP. This is also brings us one step closer to making sidecar work with local:exec, where docker does not participate.

**Comment by nonsense** [comment]
@raulk when you create a network with flannel, every host runs the `flanneld`, and every host gets a subnet lease based on the network that you have configured. I am not sure what you mean with `If flannel gives us subnet configuration, we could detect which network is which by IP.`, but it's not like you define a subnet when you run your testplan, depending where your pod/testplan container ends up at, it will pick an IP from the subnet that the host has a lease on.

Alternatively we could probably create a new flannel network (which is just a daemonset that is coordinated by etcd) per testplan (replicating what we currently do with Docker networks), but I don't know if this will scale, and sounds like a bad idea (100 `flanneld` running on every host, so that we have 100 overlay networks is wasteful).

Hence my question at https://github.com/ipfs/testground/pull/314 if we can have just one secondary overlay network to be used by all testplans, since we are not going to have concurrent testplans anyways (or are we?).

**Comment by Stebalien** [comment]
> I would support removing need for sidecar to interact with the Docker daemon to list and identify networks. If flannel gives us subnet configuration, we could detect which network is which by IP.

The sidecar still needs to use docker for networking when we're using docker networks. That's how we re-assign IP addresses.

However, we can make a k8s/cni sidecar runner that doesn't use docker. The sidecar components are pretty separate so this shouldn't (TM) be too hard.

> This is also brings us one step closer to making sidecar work with local:exec, where docker does not participate.

The main challenge is setting up all the network namespaces/interfaces. It's not really all that hard, it'll just take some fiddling (and the daemon will need to run with elevated privileges).

**Comment by nonsense** [comment]
@Stebalien the point about IP address reassignment is important, thanks for bringing it up.

1. At the moment I don't know if/how we can reassign IP addresses with Flannel - the usage docs specify that you just annotate a `pod` on startup and it will pick an IP address, based on the subnet of the host it gets scheduled at.

I am exploring other CNIs as well, such as Cilium, but this is so far an unknown for me so worth mentioning.

AFAIK the functionality for test plans to request a specific IP address from sidecar and wait for the network to be configured for them is a subset of all the other functionalities that sidecar provides (traffic shaping, latency, jitter, bandwidth, etc.).

We should decide if it is worth pursuing a setup for the MVP without possibility for reassigning IP addresses, maybe it is enough to only be able to set them up once when the container/pod is started. Does that make sense?

2. @Stebalien apart from the functionality for reassignment of IP addresses, I think there is nothing really stopping up from just getting a list of the networks from the host, and not from Docker, and running `tc` towards those interfaces, right?

**Comment by Stebalien** [comment]
> We should decide if it is worth pursuing a setup for the MVP without possibility for reassigning IP addresses, maybe it is enough to only be able to set them up once when the container/pod is started. Does that make sense?

For now that's probably fine. However, we do want to be able to change IP addresses at runtime to simulate laptops/mobile devices.

> @Stebalien apart from the functionality for reassignment of IP addresses, I think there is nothing really stopping up from just getting a list of the networks from the host, and not from Docker, and running tc towards those interfaces, right?

As long as we have some way to know which interface is which, yes. Now that we expose the IP address range to the host via a runtime variable, this should be pretty easy (look through all the interfaces for one with an IP address in the appropriate range).

**Comment by raulk** [comment]
@nonsense could you update this issue and close it if we're done here?

**Comment by nonsense** [comment]
Multus CNI and CNI-Genie are mostly similar for our purposes - they are `meta` CNI plugins, which delegate calls to real networking CNI plugins, such as Flannel, Weave, etc.

Both Multus CNI and CNI-Genie work as advertised, so we haven't encountered any major problems with them.

The discussions above resolved mostly around `sidecar` and how to make it compatible with one of the real networking CNI plugins, and we have done that with Weave for now - through the `libcni` library.

I think we can close this issue, because it was about testing Multus, which clearly works fine.
