### ISSUE TITLE
k8s + networking + traffic shaping + sidecar

### ISSUE THREAD

**Issue by raulk** [ipfs/testground#360]
This epic tracks everything related to making Sidecar work properly with k8s, with the end goal of enforcing latency traffic shaping rules per container.

**Comment by nonsense** [comment]
I think this is done. There are a few issues, such as https://github.com/ipfs/testground/issues/392 and https://github.com/ipfs/testground/issues/396 which got triggered due to bugs in the `sidecar` that are now fixed, but highlight our limited knowledge of Weave internals.

These are not critical issues for now, but we might have to dive deeper and build knowledge on Weave internals in the future in case we hit roadblocks.

**Comment by raulk** [comment]
This epic for v0.1 is done, barring these follow-ups/hardening tasks which do not deserve immediate attention: #378, #385, #392, #396. Backtracking those back into the backlog and planning them for milestone v0.2.
