### ISSUE TITLE
cluster:k8s runner: hardening

### ISSUE THREAD

**Issue by raulk** [ipfs/testground#382]
@nonsense -- can you add a checklist with things we need to harden here?

**Comment by nonsense** [comment]
This is mostly covered in https://github.com/ipfs/testground/pull/433 - the `cluster_k8s.go` was refactored, now we start `n` pods, and monitor their state and exit on success or on timeout. We could improve further by detecting error cases and failing fast (and not waiting to timeout to fail), such as all instances failing due to an image problem, etc. but this problem hasn't happened yet.
