### ISSUE TITLE
Testground roadmap/timeline

### ISSUE THREAD

**Issue by momack2** [ipfs/testground#42]
I wanted to clarify and write down our goals/expectations for Testground to ensure we stay on track. This is a continuation of the conversation @Stebalien @jimpick @raulk @daviddias and I had last week.

### Goal: Ship the next go-ipfs minor release (using testground to validate healthy network performance at scale) by *November 15th, 2019*. 

Our updated release process takes ~3 weeks from the time we cut our RC, on or before **October 25th**. 

At the time of cutting our RC, all tests need to be passing - aka, testground should have sufficient coverage to validate that master performs as well or better vs prod in simulated network conditions. Master currently has a large backlog of changes, including a large libp2p refactor IIRC, so it will probably take 2-3 weeks to use testground to validate and fix issues in master to ensure the build is green. This means we need to have testground working well enough by **~October 4th** that we can start using it (or a portion of it) to identify any bugs introduced in the stabilize branch or other areas that we want to release in 0.5.0. 

Does this seem feasible? If not, what do we need to change to hit this deadline? (parallelize more? more knowledge sharing? etc) Our goal was to get a go-ipfs release out in Q3. This new deadline, 11/15, is nearing the end of Q4 (given holidays). Delaying our next release to Q1 2020 would be unacceptable - what support / focus / etc is needed to get us on this trajectory?

**Comment by momack2** [comment]
Update - Oct 4 is not feasible given current status. 😬 We discussed how we might adjust this timeline to be feasible and landed on having **an RC cut with passing tests by Nov 15th**. This gives us another ~3 weeks in our timeline, and should still give us time to make the release before EOYear. Continuing to assume that actually landing DHT fixes will take ~3 weeks before cutting that RC _after_ Testing Infra exists, means we need to have Testing Infra up and running by **October 25th**. 

This is the most important goal of the quarter, and @daviddias will be pitching in to help shard this across more threads (folks across other working groups may get rerouted to this - either on a one-off or longer-term engagement basis - in order to ensure we hit this most important goal). 🎉

**Comment by daviddias** [comment]
Roadmap started at https://github.com/ipfs/testground/pull/75

**Comment by daviddias** [comment]
Reflecting on the quarter, team retro (#220) and the progress made on #196, I come to realize (re-learn) that for the complexity of the projects we work on, we need to detail the asks with more breath and depth, rather than compressing the whole goal into a single sentence. 

One of the best ways I found to communicate these, is to write a [PRD (Project/Product Requirements Document)](https://docs.google.com/document/d/1PbSld9mzu60qhjp7XD0LH2cpTsYnr1rVO2DANzzv0OQ/edit) so that we can have the multiple subgoals well articulated. For example, things that were unclear right up till the last week of the quarter:

- Do we need 10 Test Plans or just the DHT Test Plan?
- Do we need to test with 10000 nodes or is 100 good enough?
- Do the go-ipfs core developers need a dashboard to evaluate results? 
- What is the philosophy for the go-ipfs 0.5.0 release? Is it correctness (as communicated to the community) or is it just "something better" as suggested during the last week of the quarter?

We need to have these questions and any other requirements written down if we want to be able to have the team commit to a timeline that is achievable. Otherwise, the "best effort / wing it" mode becomes incredibly chaotic, draining and produces inferior results.

@momack2 would you be able to take this on? I think that having this doc written from the Project Lead perspective would be invaluable so that then the Architect (@raulk), the PM (me) and the rest of the team can have a proper conversation for what we are shooting for.

**Comment by bonedaddy** [comment]
If I can voice an outside opinion, code coverage of the testground itself should also be something that is considered.

The coverage right now is pretty low, so it's hard for a testing library to be considered reliable and effective when the library itself is poorly tested.

Additionally it would be nice if there could be a bit better communication about the progress of testground. It's a little concerning to have releases of go-ipfs postponed for something, and to now realize that the something we postponed for wasn't planned out.

**Comment by momack2** [comment]
Totally agree this document should exist and would significantly clarify the MVP scope. While it should absolutely synthesize information from me and Juan, I should *not* be the DRI for defining the mvp quality needed for this project. That centralizes far to much decision-making overhead on an already overloaded role trying to captain/steward the entire project. I think the best DRI for this would be the TL or PM of testground, synthesizing needs as stated from go-IPFS TL and project leadership.

**Comment by daviddias** [comment]
@bonedaddy thank you for your comment. Quoting myself from my [twitter response to your feedback](https://twitter.com/daviddias/status/1211751996195328000) just so it doesn't get lost:

> We plan, experiment, retrospect, learn, iterate and go at it again. Building software is a continuous cycle, not a race. What we got from building Testground and scaling a test to a couple of thousand instances will be incredibly useful for the work to happen in Q1.

We are not way better prepared than ever, to refine Testground and the Test Plans we created, something that would not have been possible if we didn't give it a try with what was our knowledge back then.

--------------------------------

> Totally agree this document should exist and would significantly clarify the MVP scope.... @momack2 

Understood. Now that we on schedule to get all of those folks in sync time, we can go through the list, have the conversation of what is possible in what time frames and narrow down the exact list of goals we will be shooting for, so that we all understand and agree from the start.
