### ISSUE TITLE
Test the TestGround

### ISSUE THREAD

**Issue by daviddias** [ipfs/testground#54]
A few people have reported being uncertain if TestGround is buildable or if they just don't have the right setup in their machine.

Given that TestGround is designed to be runnable in a local node for non exhaustive tests. Having a Test Plan that is designed so that we check that a TestGround is buildable on Travis (and therefore, granting that it is buildable at least for its essential features) would be a great thing.

Looking for a comment on _how urgent_ should this be and/or if there is any reason to not do it.

**Comment by jimpick** [comment]
100% agree that it should be tested in CI.

Travis is OK for unit tests, but to do it right, I think we should do some automation where we spin up a test cluster for each commit (or nightly if it's too expensive) and put it through a smoke test just so that we have confidence that it's useable for real testing and we can catch regressions early.

**Comment by raulk** [comment]
Oh yeah, the testground should be unit and integration tested. We need to set up CI; for unit tests that’ll be easy, for integration tests (e.g. sync service tests that rely on Redis), it could be a bit more intricate.

**Comment by raulk** [comment]
And we need instructions for building and running this thing.

**Comment by daviddias** [comment]
> And we need instructions for building and running this thing.

Improved a bit with #51

**Comment by jimpick** [comment]
We do have CI tests running at: https://travis-ci.com/ipfs/testground

Can this be closed?

**Comment by daviddias** [comment]
It is true that we started running "something" on CI, but we are far from having the practice of adding tests to our PRs. 

@hacdias is adding codecov check to see how far are we from a better state https://github.com/ipfs/testground/pull/244/files

**Comment by daviddias** [comment]
As of today, we only have 17% test coverage  https://github.com/ipfs/testground/pull/244#issuecomment-564679067

A reasonable goal should be at least 80%

**Comment by jimpick** [comment]
Sounds like this is an epic. I'll add the label.

**Comment by nonsense** [comment]
Let me explain why I am against 80% test coverage. This is a made up number - why not 60% or 90% or 100%? This is not a number you can put in an automated system and expect to increase the quality of the project.

I completely agree that we need more testing, but not by enforcing test coverage.

The requirements for Testground and the initial MVP setup is changing daily. I suggest we lock the behaviour of the system by having a small number of integration tests, rather than focusing on code coverage.

Another point is that codecov currently introduces noise, because it is not required, but PRs that don't pass it appear as if they have broken the tests. Therefore developers must look into each test run to determine if the `required` tests have passed, or just codecov has failed.
