### ISSUE TITLE
"error during end metric push" (prometheus-pushgateway) with local:docker runner

### ISSUE THREAD

**Issue by sebastiendan** [ipfs/testground#637]
#### Version information:
[d44b90430969bc0f90092f6644f54a195e9380c3](https://github.com/ipfs/testground/commit/d44b90430969bc0f90092f6644f54a195e9380c3)

OS: MacOS

#### Description:
Getting through the [USAGE.md](https://github.com/ipfs/testground/blob/master/docs/USAGE.md) up to the dht/find-peers test I see a long list of errors related to `periodic metric push` to `http://prometheus-pushgateway:9091`.

I can see latest commit with [#606 ](https://github.com/ipfs/testground/pull/606) is supposed to have introduced this metric push for the k8s runner.

But it seems the push is also (wrongly?) triggered when using the local:docker runner.

Side note: I cannot really understand from USAGE.md whether there's a way to visualize my test run results besides my terminal output.

I've started recently an [effort](https://github.com/sebastiendan/ipfs-perfs) to challenge IPFS performances and found out about your project today. 
My understanding is that TestGround would be a good option to execute custom performance tests such as triggering consecutive `add` and `get` calls, returning execution times and plotting them with Grafana/Kibana.

Am I correct in my assumption or is this off-topic?

**Comment by raulk** [comment]
@sebastiendan Thanks for posting this issue! This is a known issue, and @coryschwartz is fixing it in https://github.com/ipfs/testground/issues/660.

Recently we added the ability for test instances to publish Prometheus metrics via the RunEnv. The new APIs are here:

https://github.com/ipfs/testground/blob/master/sdk/runtime/metrics.go#L17-L52

Given that test instances are ephemeral jobs, they are not eligible for being scraped by Prometheus. That's why the test runner pushes these metrics to the Prometheus pushgateway.

Unfortunately, the code we merged in https://github.com/ipfs/testground/pull/606 assumes that a Prometheus pushgateway will always be available at the `prometheus-pushgateway` hostname, which is the case if you're running in the k8s cluster environment that our infra scripts set up, but not in other scenarios. 

This will be fixed by introducing the relevant healthchecks in all runners.

**Comment by raulk** [comment]
BTW -- this is simply a warning, consider it a red herring if you're not interested in using Grafana. It has no impact in the execution of the test. If all you want to do is collect the metrics you explicitly output (runenv.RecordMetric), you can use the `--collect` flag when running the test, and you'll get a zip bundle with all metrics outputted by all instances.

**Comment by sebastiendan** [comment]
Thanks for the update.

I had given a try to the `collect` cli command on a previous run and hadn't found what I was looking for. On a different test (`benchmarks/all`) I can see metrics in the run.out.

I'll probably try to write my own tests to have an idea of the benefits of testground in my use case.

**Comment by raulk** [comment]
Bug is tracked in https://github.com/ipfs/testground/issues/660.

**Comment by Robmat05** [comment]
As #660 is scheduled to be completed in this v0.3 sprint and it resolves this bug. I am closing this ticket as duplicate
