### ISSUE TITLE
Contrast Testground and Testlab

### ISSUE THREAD

**Issue by jimpick** [ipfs/testground#64]
The [libp2p testlab](https://github.com/libp2p/testlab) project is a preceding framework initiative to build a system for running large distributed test cases.

The [testground spec](https://github.com/ipfs/testground/blob/master/docs/SPEC.md) mentions it in the "Incremental Implemention Plan":

> Study how libp2p/testlab can cover the distributed deployment requirements of this design, and understand how it can be reused within this context.
>
> Initial assessment:
> 
> * The current version can be regarded as a domain-specific deployer, capable of launching p2p and ipfs daemons (PR in review) in a Nomad cluster. It does not use Docker, nor does it have support for deploying test logic. It essentially schedules N containers in a cluster, and returns the API multiaddrs to the scheduling process to enable creating client stubs for control, from the code that launched the deployment.
> * In some ways, it can be regarded as a cloud-native iptb.
> * The observability/monitoring/metrics elements are not yet developed.

Testlab's [roadmap](https://github.com/libp2p/testlab/blob/master/ROADMAP.md) covers some of the same ground as the spec for Testground. [IPFS support using Docker](https://github.com/libp2p/testlab/pull/20) exists as a PR (starts IPFS nodes and connects them, but no scenario yet).

Testground has a similar approach to writing test code, using a config file + go logic.

Testground:

* [manifests/dht.toml](https://github.com/ipfs/testground/blob/master/manifests/dht.toml)
* [plans/dht/lookup_peers.go](https://github.com/ipfs/testground/blob/master/plans/dht/lookup_peers.go)

Testlab:

* [examples/test.json](https://github.com/libp2p/testlab/blob/master/examples/test.json)
* [examples/pubsub_scenario/pubsub_scenario.go](https://github.com/libp2p/testlab/blob/master/examples/pubsub_scenario/pubsub_scenario.go)

The Testlab "deployment configuration" JSON file is being used to declaratively describe stages which are transformed via plugins into deployable sets of software controlled by nomad. The test code execution is baked into the "scenario" binary that gets deployed in the final stage.

Contrasting that, the Testground "manifest" TOML file appears to be used to specify a series of individual tests, but the go code is responsible for launching any instances itself - for example, the "smlbench" test uses (currently disabled) the "IPTB ensemble" wrapper that is part of the [Testground SDK](https://github.com/ipfs/testground/tree/master/sdk/iptb).

There are many other differences. As both projects are out there, and represent different design choices, it might be good to capture the "why?" and how that relates to the core needs and desires for a large scale test framework. There remains the possibility of utilizing some or all of Testlab with Testground ... but they do appear to be competing on the basis of how they are configured and tests are written, so it may make more sense to deprecate one in favour of the other if we are only going to pursue development on one of them.

This issue is a bit of a placeholder ... we could choose to do more "study" (as suggested in the spec) or we could add some documentation.

**Comment by raulk** [comment]
Initial answers. Please ask me to elaborate further on the points that you remain uncertain about!

* The testlab is a workload launcher: that's only one piece of the puzzle.
* It is tightly coupled to Nomad. This is impractical when developing tests and iterating rapidly. That's why we have pluggable builders and runners -- so we can develop tests locally.
* It does not solve important requirements: comparative testing, GitHub integration, metrics collection _for a specific set of upstream dependencies_, network simulation, building against a concrete set of versions of upstreams, coordination across instances via state signalling in a, e.g. ~10000 node cluster. To illustrate the last point, it's not defined how an instance would add a random file locally and would communicate the CID to all other instances participating in that test.
* Is not intended as a continuously running service (daemon), at least it's not captured in the roadmap.
* Launches IPFS daemons or libp2p daemons. Relies on hitting those processes from the outside via their public API, which does not work for us. For example, there are lots of knobs we wanna adjust in libp2p (e.g. bucket size in the DHT, gossipsub degree, stream timeouts, etc.) which we can't do externally by interfacing with the daemon -- unless we expose every single little thing we need to tweak. This is impractical. Such tests require programmatic access to IPFS and libp2p.

With regards to the configuration files, note that they are used for different purposes. In testlab, they are a DSL that gets turned into Nomad HCL. In testground, the toml files are a "bill of materials" for testplans -- indicating which test cases exist, config parameters, etc.

How do you envision using Testlab within Testground? Maybe you can elaborate. The way I see it, the goal of Testlab was less ambitious than Testground, and when expanded to encompass everything we actually need to incorporate distributed testing into our continuous software engineering lifecycle, we can't reuse the code of Testlab (we _did_ reuse its learnings!) because of fundamental decisions that are incompatible with the aims of Testground.

But I'd love it if you could be more specific about how you'd see the integration happening.

**Comment by jimpick** [comment]
I'd love to hear @bigs perspective on the above points. It sounds like testlab should be deprecated in favour of this project if we're not planning to invest any more into it.

**Comment by raulk** [comment]
@jimpick Curious what are your outstanding doubts? @bigs has been participating in calls and document review all along, and I've chatted with him several times about testground/testlab and all the elements I mentioned above. How does declaring another project deprecated help us make progress in our (ambitious) goals for testground? I think I'm missing something!

**Comment by jimpick** [comment]
@raulk No doubts ... just opened this issue after discussion with @david and we both felt it would be good to document architectural choices between similar test framework initiatives in github. I only suggested that marking testlab as deprecated as a housekeeping task to make clear to the public that testground is the active project.

**Comment by jimpick** [comment]
On the other hand, maybe testlab is not an inactive project?

**Comment by daviddias** [comment]
Thank you @raulk for providing this background!

> just opened this issue after discussion with @david and we both felt it would be good to document

Reading @raulk's notes, I feel that he just did. I'm happy to take these into the SPEC document and create a section on previous art.

**Comment by raulk** [comment]
Seems like the questions in this issue have been answered. Closing it; feel free to reopen if clarifications are needed.
