### ISSUE TITLE
Contrast Grafana vs. Kibana

### ISSUE THREAD

**Issue by jimpick** [ipfs/testground#68]
This issue is here to collect experiences of Grafana vs. Kibana so we can make some decisions about which ones to use...

**Comment by raulk** [comment]
Grafana is great at infrastructure monitoring and dashboards, it's metric-oriented, and capable of aggregating multiple data sources. The strong suit of Kibana is its querying/exploratory functionality for structured or unstructured logs, as well as its dashboarding. It's still principally a time-series oriented UI, but its drill-down/filtering capabilities are off-the-charts (pun intended).

Kibana is super powerful when building queries that slice and dice basically anything (any data type), and it's especially useful in correlating all charts/dashboards/tables to contextualise them to the query you typed in. Kibana used to present data in time bucket aggregations, but since they introduced Timelion, time-series oriented analytical visualisations are possible. (Apparently it can now work with multiple data sources, but I don't expect to use that feature).

They are essentially two different beasts, built for different things. You can use Kibana for what you'd use Grafana, but it does not work the other way round, because Kibana relies on the query backend of Elasticsearch to resolve loose queries like "show me everything available under this run ID, or under this branch, or for this commit". We won't be able to do that with Grafana (at least not easily).

^^ This is not a complete comparison, just my thoughts knowing both tools very well and having used them in several projects in the past.

**Comment by jimpick** [comment]
I think @raulk answered this fairly well, so I'll close this.
