### ISSUE TITLE
In search of a sane k8s runner initialization.

### ISSUE THREAD

**Issue by coryschwartz** [ipfs/testground#680]
At present, the k8s runner is initialized by initRunner. This is the method that establshes the work pool, among other things. There are several code paths through which initRunner may be invoked for the first time.

Some methods require an initialized pool, but lack other configuration information. For example, the Healthcheck method added https://github.com/ipfs/testground/pull/623 lacks the input required to pass to initRunner, and yet needs the work pool to be available to perform checks.

@raulk makde the following suggestions which seem pretty reasonable to me:

https://github.com/ipfs/testground/pull/623#discussion_r391569500

```
Yeah, the init logic needs to be untangled. It ends up initialising a singleton k8s runner with the configuration it first sees. But that config is really a run-specific configuration, so it's incorrect to globally initialise the runner with it.

IMO, what should happen is:

Healthcheck checks and/or initialises a pool (fix action) by picking up the Kubernetes config from the env (Engine.EnvConfig()), or defaulting to the default configuration.
The podResourceCPU and podResourceMemory state variables that are populated on init from the first run configuration we see should not be in the state of the runner. They should be calculated per-run.
I don't understand why c.maxAllowedPods is even in the state of the runner -- it's calculated every time a run happens, and it's racy under a concurrent scenario.
```

**Comment by Robmat05** [comment]
Cool, We’ll talk about putting this into the v0.4 sprint starting Mar 17

**Comment by nonsense** [comment]
I am picking this up now.

To answer some of the questions from @raulk and @coryschwartz while I was away:

```
> Yeah, the init logic needs to be untangled. It ends up initialising a singleton k8s runner with the configuration it first sees. But that config is really a run-specific configuration, so it's incorrect to globally initialise the runner with it.
```
The idea is to have a global pool of connections to Kubernetes, so I initialised the k8s runner as a singleton on purpose. If we have 10 concurrent testplan runs, we don't want to have 10 pools of 20 connections to the Kubernetes API.

```
Healthcheck checks and/or initialises a pool (fix action) by picking up the Kubernetes config from the env (Engine.EnvConfig()), or defaulting to the default configuration.
The podResourceCPU and podResourceMemory state variables that are populated on init from the first run configuration we see should not be in the state of the runner. They should be calculated per-run.
```

Not sure what is the benefit of calculating `podResourceCPU` and `podResourceMemory` per-run, when these are static values that are set once the `testground daemon` starts.

```
I don't understand why c.maxAllowedPods is even in the state of the runner -- it's calculated every time a run happens, and it's racy under a concurrent scenario.
```
1. It is calculated on every run, because the cluster size might have changed. I might have 3 nodes now, and 30 nodes 30min from now.
2. The `maxAllowedPods` is really a guideline, not a strict limit, it will always be racy, because ultimately it depends on the size of the cluster and what this cluster is running, and this is ortogonal to testground - we run monitoring, networking daemons and what-not, so it is hard for testground to always have a perfect answer for `how many testplans am I allowed to run`.
At the same time I don't want developers to try to run 3000 testplan instances on 3 node clusters.
