### ISSUE TITLE
sidecar crashes if redis is unavailable

### ISSUE THREAD

**Issue by coryschwartz** [ipfs/testground#691]
This was reported by  @aschmahmann. He demonstrated an issue in which the redis server hit its connection limit, the sidecar would also crash, and tests were left unable to move forward beyond the network initialization phase.

When this happeens, there is no automated recovery, and no obvious way for users to understand what is going on.

Although I was never able to reproduce the port exhaustion as he was seeing, I  am able to able to produce a similar outcome by simply killing the redis container as soon as it is started.

I think there are a couple of things we could do to improve the situation.
It occurs to me that the kubernetes runner will restart the pods when a crash occurs, but that same experience is unmet in the local docker runner, even though it could easily be made to do so.

1. Start local docker containers with a restart policy, so they are restarted when/if they crash.
2. Don't crash when partitioned from the redis server. Maybe implement backoff retries.

**Comment by raulk** [comment]
In this case, we should fail the test run, and report what happened. We shouldn't recover automatically. It would be useless in this case, since we anyway run Redis with no persistence.

An attempt to recover will anyway be performed by a subsequent test run, which will implicitly call the healthcheck/fix logic that will notice Redis, sidecar, etc. are absent, and will start them again.

**Comment by nonsense** [comment]
I'd rather we do 1, than 2. Adding recovery logic, backoff retries, etc. makes the code complicated and Redis should really be available. The sync service is critical, we should not be adding work arounds for it, while it is not there.
