### ISSUE TITLE
Metrics don't delete after plan is finished

### ISSUE THREAD

**Issue by coryschwartz** [ipfs/testground#745]
slack discussion: https://protocollabs.slack.com/archives/CLF3S2NJC/p1585228288075000

Once a plan has run its course, the metrics collected persist forever. From a usage perspective, these metrics are annoying because they are frequently not relevant to the current test being performed, and filtering out only the current test metrics is more arduous than would otherwise be necessary.

Additionally, the size of accumulated metrics which prometheus must include in its scrapes will become large over time and will eventually cause failures due to their size.

As discussed in the slack message linked, the pushgateway we are using does not support TTLs or any automatic metric expiry. Until a better solution is devised, for now, lets delete the metrics from the pushgateway at the end of a successful or unsuccessful runs.

- [x] Quick fix: Deleting after successful is pretty easy and works. I tried this successfully in https://github.com/ipfs/testground/pull/744
- [ ] The code added in https://github.com/ipfs/testground/pull/744 is never hit if the containers/pods are simply deleted. Deal with this.
- [ ] Find a permanent fix. Discussion open about using a push model with InfluxDB or Elasticsearch as our store.

**Comment by raulk** [comment]
@nonsense can you add your notes here on why the Pushgateway maintainers have rejected adding a TTL feature?

I'm thinking about forking pushgateway in order to add the concept of _sessions_.

1. When starting, a test plan would open a _session_, associated with the groupings it has picked.
2. It would push its metrics under that grouping.
3. Upon end, it would close the _session_.

On the pushgateway side:

1. Opening a _session_ causes us to track if those metrics have been scraped by Prometheus.
    * Every time new metrics are pushed, we reset `scraped[session_id]=false`.
    * Every time Prometheus scrapes us (we identify Prometheus by the [`User-Agent`](https://github.com/prometheus/prometheus/pull/2447) and the `Accept` headers), we set `scraped[session_id]=true`.
2. Closing a _session_ causes us to expunge all the metrics associated with the _session_ once `scraped[session_id]=true`.

---

I'd like to hear your conclusions on the TTL story, to evaluate if this feature would be accepted upstream.

**Comment by nonsense** [comment]
> can you add your notes here on why the Pushgateway maintainers have rejected adding a TTL feature?

`First of all, the Pushgateway is not capable of turning Prometheus into a push-based monitoring system.`

`The Pushgateway is a metrics cache. It does not have statsd-like semantics.`

`The metrics pushed are exactly the same as you would present for scraping in a permanently running program.`

---

https://groups.google.com/forum/#!topic/prometheus-developers/9IyUxRvhY7w

https://github.com/prometheus/pushgateway/issues/19


`we actively discourage
users from using the Pushgateway to turn Prometheus into a push-based
monitoring system. You are of course free to create tooling to use
Prometheus in ways it is not intended to be used in, but you also have
to understand that the developers of the core components don't want to
add features that go against the fundamental concepts of Prometheus
(plus take the burden of maintaining said features and deal with the
(from their perspective predictable) issues those features will
cause).`

`I'd say if each instance of these short-lived jobs are
single-shot “unique” tasks, i.e. “at” style rather than “cron”
style, with a certain amount of information to be persisted
outside as the task reaches the end of its short lifetime, as I
understand you, then this really looks like event-logging. I
don't have all the information for a detailed analysis, but in
general Prometheus is utterly inappropriate for
event-logging.`

`Solution: Do _not_ implement a TTL. Instead, make metrics
deletion (with a simple DELETE call of the RESTful API) a part of
decommissioning a job.`

`What I would recommend is that
whatever precedure is taken to create a job and then eventually remove
a job from the scheduler also has the responsibility to remove metrics
from the Pushgateway. That's a single DELETE call, if need be easily
implementable via a `curl` command, and should be easily automatable.`

`Currently we have a custom sidecar on the pushgateway that checks for metrics older than 30 seconds, and clears them down.  When you have no option but to push metrics, than scrape, what is the better solution?`

---

Seems like the `short-lived unique jobs` use-case is not supported for Prometheus.

It looks like we have a few solutions:
1. `sidecar` to clear old metrics as suggested above
2. send a DELETE at the end of a testplan - the problem we have is if an operator runs a `kubectl force delete` bypassing `testground`. this is what we currently do.
3. deploy and register individual pushgateway as part of a testplan run? then we could make sure it gets removed alongside any testplan instances.

I'd like to avoid having to fork pushgateway for a number of reasons, that I suggest we don't include in this ticket.

**Comment by raulk** [comment]
Thanks for the investigation. This just reinforces my original events-based model thinking. We just happened to organically adopt Prometheus here, counter to the original vision.

---

Counterpoints to the solutions you suggested:

1. We run one sidecar per node, and one centralised pushgateway. This won't work well. It would require consensus, or having each sidecar own only the metrics for its adjacent containers -- unnecessarily complex. And it's also not sidecar's responsibility.
2. OK as an immediate patch; terrible in all senses (coupling, incomplete solution, edge cases, vulnerable to scraping hiccups, etc.)
3. Oh, boy, no 😆 Unnecessary complexity, 

---

This is what I'm thinking:

* Short-term: test plan DELETEs its metrics after 10 seconds (note: also introduces a 10 sec latency before the test officially finishes -- bummer).
* Medium-term: fork pushgateway to introduce sessions, which will completely address the problem. Propose the enhancement upstream.
* Long-term: move off Prometheus. Metrics shipping is not the only problem. Tests really do not have "ongoing metrics" (which is what Prometheus is good for), they produce events, which happen to be metrics.

**Comment by nonsense** [comment]
> Thanks for the investigation. This just reinforces my original events-based model thinking. We just happened to organically adopt Prometheus here, counter to the original vision.

This is not the take-away I am making from the thread.

My take-away is that Prometheus is not designed for a push based model and is not supporting out of the box `short-lived unique jobs pushing metrics to it, and then disappearing` - this is essentially what a test plan with 10k instances is.

---

With respect to event-based logging and stats logging - these are completely different types of observability tools and have their pros and cons.

In a nutshell:
1. Metrics / stats scale with the number of measurements and are constant with respect to instances and load.
2. Events / Logs scale with the load of an application.

Suggesting to move to event-based model to me means we are dropping metrics altogether, and just utilising events / logs for the observability of testplans, which seems sub-optimal and doesn't scale well for the number of instances we plan to support - testplans with 10k instances and beyond.

Related:
https://www.oreilly.com/library/view/distributed-systems-observability/9781492033431/ch04.html
https://peter.bourgon.org/blog/2017/02/21/metrics-tracing-and-logging.html

**Comment by Robmat05** [comment]
#755 relates to the third checkbox on finding a permanent fix

**Comment by coryschwartz** [comment]
We have decided to remove the pushgatway even with an alternative not yet implemented. Pushgateway is being removed.

**Comment by coryschwartz** [comment]
Additionally, we should close https://github.com/ipfs/testground/issues/711 and https://github.com/ipfs/testground/issues/748 once https://github.com/ipfs/testground/pull/848 is merged.
