### ISSUE TITLE
Redis starts with THP enabled.

### ISSUE THREAD

**Issue by coryschwartz** [ipfs/testground#767]
Transparent huge pages was disabled by adding the configuration to `dummy.yml`. However this dependency was not taken into consideration when redis moved to the helm chart.

As a result, redis starts with transparent huge pages enabled.

The dependencies need to be de-tangled. dummy.yml configures the host (particularly, to disable transparent_hugepages), therefore, it is a prerequisite for starting redis.

The weave service monitor should be installed after the prometheus operator because it relies on a CRD added when the operator is installed.

What I am considering is to remove setting this up in dummy.yml and do it instead using kops:

[kops documentaiton](https://github.com/kubernetes/kops/blob/master/docs/cluster_spec.md#setting-custom-kernel-runtime-parameters) has instructions about how to do this.

**Comment by nonsense** [comment]
> The dependencies need to be de-tangled. dummy.yml configures the host (particularly, to disable transparent_hugepages), therefore, it is a prerequisite for starting redis.

Note that other daemonsets (such as `sidecar`) are also dependent on the the `dummy` daemonset. This is enforced with `initContainer`, see: `infra/k8s/sidecar.yaml` and
`while [ "$GW" = "" ]; do export GW=$(ip route | grep cni0 | awk '{print $7}'); echo "Got GW: $GW"; sleep 5; done;`

`cni0` is added by the first pod created on a given host, and is a workaround for https://github.com/coreos/flannel/issues/1243

Mentioning this, because these dependencies are indeed very important.

---

> What I am considering is to remove setting this up in dummy.yml and do it instead using kops: kops documentaiton has instructions about how to do this.

I wasn't aware of that - looks like a better solution, go for it!

We would still have the dependencies in `dummy` due to `cni0`, but the fewer dependencies the better!
