### ISSUE TITLE
redis dial tcp i/o timeout and probes failures

### ISSUE THREAD

**Issue by nonsense** [ipfs/testground#795]
When running the `gossip-sub` testplans with many instances, we get the following error on a few of them:

```
{"type":"finish","outcome":"failed","error":"error waiting for discovery service: failed to write to pubsub subtree in sync service: dial tcp 100.96.4.4:6379: i/o timeout"}}
```

---

Related chunk of the code:

```
	watcher, writer := tgsync.MustWatcherWriter(ctx, runenv)

	// TODO: figure out why closing the watcher / writer sometimes blocks for ~3m.
	// defer watcher.Close()
	// defer writer.Close()

	localPeer := *host.InfoFromHost(s.h)
	entry := PeerRegistration{Info: localPeer, NType: nodeType, NodeTypeSeq: nodeTypeSeq, NodeIdx: nodeIdx}
	st := &tgsync.Subtree{
		GroupKey:    "pubsub-test-peers",
		PayloadType: reflect.TypeOf(&PeerRegistration{}),
		KeyFunc: func(val interface{}) string {
			return val.(*PeerRegistration).Info.ID.Pretty()
		},
	}
	if _, err := writer.Write(ctx, st, &entry); err != nil {
		return nil, fmt.Errorf("failed to write to pubsub subtree in sync service: %w", err)
	}

```

Basically the sync service `writer.Write` is failing.

---

Also the healthcheck probes on Redis fail, so k8s kills Redis

```
  Warning  Unhealthy               2m55s (x3 over 3m5s)  kubelet, ip-172-20-38-113.eu-central-1.compute.internal  Liveness probe failed:
  Warning  Unhealthy               2m54s (x3 over 3m4s)  kubelet, ip-172-20-38-113.eu-central-1.compute.internal  Readiness probe failed:
```

Looking at the Grafana charts collecting metrics from Redis, it didn't appear that Redis is unhealthy.

Checking the kubelet and syslog logs on the Redis machine, also didn't show any issue.

---

This could be an issue with Redis or Flannel or something else.

**Comment by raulk** [comment]
Some thoughts:

- The healthchecks hit Redis via localhost. Given that they fail, this rules out Flannel as a culprit, as the healthchecks don't involve a flannel interface.
- Redis seems to be happily responding to queries in sub-ms response time. Also, it prints no logs about an unhealthy state before being killed. Root cause doesn't seem to be in Redis with this info.
- I suspect something's going on at the kernel/cgroups level inside the Redis container; potentially conntrack.

I suggest we check the conntrack and network stats reported by node_exporter (at the VM level), and check the diagnostics at the container level (e.g. ServiceMonitors)?

**Comment by dirkmc** [comment]
I believe the root cause of the issues we were seeing may be related to https://github.com/ipfs/testground/issues/686
