### ISSUE TITLE
testground-infra chart appears to be racy

### ISSUE THREAD

**Issue by nonsense** [ipfs/testground#818]
The `helm install testground-infra .` seems to be racy and sometimes fails with the following.

```
Installing Testground infrastructure - prometheus, pushgateway, redis, dashboards
~/code/src/github.com/ipfs/testground/infra/k8s/testground-infra ~/code/src/github.com/ipfs/testground/infra/k8s
walk.go:74: found symbolic link in path: /Users/nonsense/code/src/github.com/ipfs/testground/infra/k8s/testground-infra/charts/testground-dashboards/dashboards resolves to /Users/nonsense/code/src/github.com/ipfs/testground/dashboards
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "nsm" chart repository
...Successfully got an update from the "ethersphere" chart repository
...Successfully got an update from the "stable" chart repository
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 4 charts
Downloading prometheus-operator from repo https://kubernetes-charts.storage.googleapis.com/
Downloading prometheus-pushgateway from repo https://kubernetes-charts.storage.googleapis.com/
Downloading redis from repo https://charts.bitnami.com/bitnami
Dependency testground-dashboards did not declare a repository. Assuming it exists in the charts directory
walk.go:74: found symbolic link in path: /Users/nonsense/code/src/github.com/ipfs/testground/infra/k8s/testground-infra/tmpcharts/testground-dashboards/dashboards resolves to /Users/nonsense/code/src/github.com/ipfs/testground/dashboards
Deleting outdated charts
walk.go:74: found symbolic link in path: /Users/nonsense/code/src/github.com/ipfs/testground/infra/k8s/testground-infra/charts/testground-dashboards/dashboards resolves to /Users/nonsense/code/src/github.com/ipfs/testground/dashboards
Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "Prometheus" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "PrometheusRule" in version "mon
itoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"]
Error on line 128
```

It looks like `push-gateway` is dependent on the `prometheus-operator`, but this relationship doesn't seem to be in effect within the helm chart.

**Comment by nonsense** [comment]
cc @coryschwartz in case you know how to fix this easily.

**Comment by coryschwartz** [comment]
The dashboards are dependent on prometheus-operator since it is just a ConfigMap -- whatever was installed The messages saying `walk.go:74: found symbolic link...` is normal, there is a symbolic link there to the dashboard files. 

The error after those messages says something is adding a PrometheusRule and ServiceMonitor before the operator is setup.

```
Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "Prometheus" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "PrometheusRule" in version "mon
itoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
```

Both Redis and the Pushgateway would create a ServiceMonitor, though I could not reproduce this error after several re-installations. To force the error, I commented out the prometheus operator section in testground-infra/requirements.yaml so that only redis, the pushgateway, and the dashboards would be installed. In this configuration I could get a similar error.  In this configuration, I was able to get one of the errors you saw.

```
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
Error on line 134
```

The way to declare chart dependencies, is creating nested subcharts.  When all the subcharts are at the same level, resources are sorted by kind.  The known types are here:
https://github.com/helm/helm/blob/9b42702a4bced339ff424a78ad68dd6be6e1a80a/pkg/releaseutil/kind_sorter.go#L27
CustomResourceDefinitions are included in the list. When the promehteus-operator chart is included, it adds a CustomResourceDefinition for the ServiceMonitor. The ServiceMonitor would be added after this point by the kind sorting. (see sortManifestsByKind and lessByKind in the same file)

I don't know it's possible to encounter this error unless there was an error applying the ServiceMonitor CRD so that later applying the ServiceMonitor failed. I can't get this to happen under normal circumstances.


I would **rather** declare dependencies in the chart than by the order of install, but I don't see a way to do that. I'll make a PR which removes the prometheus-operator from the chart and installs it in the install script :/

**Comment by nonsense** [comment]
> I would rather declare dependencies in the chart than by the order of install, but I don't see a way to do that.

I don't know `helm` very well, but reading the docs and similar questions on the internet, it looks like this is not possible right now.

So we have to resort to order of install or some other method.
